# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
jobs:
- deployment: Development
  environment:
    name: United States - Development
    resourceType: Kubernetes

  strategy:
    runOnce:
      deploy:
        steps:
        - script: pwd && ls -lah && cd $(Pipeline.Workspace) && pwd && ls -lah
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'kubernetesServiceConnection'
            kubernetesServiceConnection: 'United States - Development-camunda-eastus-dev-aks-wyattadotestdeleteme-1706022020295'
            namespace: 'wyattadotestdeleteme'
            manifests: 'deployment.yaml'


